#!/usr/bin/env bash
set -e

#python3 is already installed
sudo apt update
sudo apt install virtualenv

#sudo apt-get install tmux

sudo ufw enable
sudo ufw allow http
sudo ufw allow 8050
sudo ufw status



