#!/usr/bin/env bash
set -e

mkdir test
cd test

git clone https://github.com/mounesi/pa.git

virtualenv -p python3 ./venv
source ./venv/bin/activate
python -c "import os;print(os.path)"

pip install notebook
pip install plotly
pip install pandas
pip install dash

pwd

